// This file was generated by iot-lvgl-service
// LVGL version: 8.3.6

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
// SCREEN: ui_Screen_rGKsRocq
void ui_Screen_rGKsRocq_screen_init(void);
lv_obj_t * ui_Screen_rGKsRocq;
lv_obj_t * ui_Image_rDI5MBN1;
lv_obj_t * ui_Arc_3EtQ_WHD;
lv_obj_t * ui_Label_sX8ziDB5;
lv_obj_t * ui_Image_wp3wpZoQ;
lv_obj_t * ui_Imgbutton_evnVpoZ1;
lv_obj_t * ui_Image_ronkrDQc;
lv_obj_t * ui_Imgbutton_ona_PBbd;
lv_obj_t * ui_Imgbutton_bj2KQu_x;
lv_obj_t * ui_Imgbutton_1Rq8MsWo;
lv_obj_t * ui_Label_OyXxwNmi;
lv_obj_t * ui_Label_3cbfZoEk;
lv_obj_t * ui_Label_3ulSxW9v;
lv_obj_t * ui_Label_mCYBirzL;
lv_obj_t * ui_Label_pNGqdf8X;
lv_obj_t * ui____initial_actions0;



///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void) {
	lv_disp_t * dispp = lv_disp_get_default();
	lv_theme_t * theme = lv_theme_default_init(dispp,
		lv_palette_main(LV_PALETTE_BLUE),
		lv_palette_main(LV_PALETTE_RED),
		false,
		LV_FONT_DEFAULT);
	lv_disp_set_theme(dispp, theme);
	ui_Screen_rGKsRocq_screen_init();
	ui____initial_actions0 = lv_obj_create(NULL);
	lv_disp_load_scr(ui_Screen_rGKsRocq);
}
