// This file was generated by iot-lvgl-service
// LVGL version: 8.3.6

#ifndef _PROJECT_UI_H
#define _PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen_rGKsRocq
void ui_Screen_rGKsRocq_screen_init(void);
extern lv_obj_t * ui_Screen_rGKsRocq;
extern lv_obj_t * ui_Image_rDI5MBN1;
extern lv_obj_t * ui_Arc_3EtQ_WHD;
extern lv_obj_t * ui_Label_sX8ziDB5;
extern lv_obj_t * ui_Image_wp3wpZoQ;
extern lv_obj_t * ui_Imgbutton_evnVpoZ1;
extern lv_obj_t * ui_Image_ronkrDQc;
extern lv_obj_t * ui_Imgbutton_ona_PBbd;
extern lv_obj_t * ui_Imgbutton_bj2KQu_x;
extern lv_obj_t * ui_Imgbutton_1Rq8MsWo;
extern lv_obj_t * ui_Label_OyXxwNmi;
extern lv_obj_t * ui_Label_3cbfZoEk;
extern lv_obj_t * ui_Label_3ulSxW9v;
extern lv_obj_t * ui_Label_mCYBirzL;
extern lv_obj_t * ui_Label_pNGqdf8X;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_beijing_png_png);
LV_IMG_DECLARE(ui_img_dianliangzhengchang_png_png);
LV_IMG_DECLARE(ui_img_fengsu_png_png);
LV_IMG_DECLARE(ui_img_kaiqi_png_png);
LV_IMG_DECLARE(ui_img_moshi_png_png);
LV_IMG_DECLARE(ui_img_shangjiantou_png_png);
LV_IMG_DECLARE(ui_img_xiajiantou_png_png);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
