// This file was generated by iot-lvgl-service
// LVGL version: 8.3.6

#include "../ui.h"


static lv_obj_t * g_kb_screen;
static void kb_screen_event_cb(lv_event_t *e)
{
	lv_event_code_t code = lv_event_get_code(e);
	lv_obj_t *kb = lv_event_get_target(e);
	if(code == LV_EVENT_READY || code == LV_EVENT_CANCEL){
		lv_obj_add_flag(kb, LV_OBJ_FLAG_HIDDEN);
	}
}

void ui_Screen_rGKsRocq_screen_init(void) {
	ui_Screen_rGKsRocq = lv_obj_create(NULL);

	g_kb_screen = lv_keyboard_create(ui_Screen_rGKsRocq);
	lv_obj_add_event_cb(g_kb_screen,kb_screen_event_cb,LV_EVENT_ALL,NULL);
	lv_obj_add_flag(g_kb_screen,LV_OBJ_FLAG_HIDDEN);
	lv_obj_set_scrollbar_mode(g_kb_screen,LV_SCROLLBAR_MODE_OFF);
	lv_obj_clear_flag(ui_Screen_rGKsRocq,LV_OBJ_FLAG_SCROLLABLE);


	ui_Image_rDI5MBN1 = lv_img_create(ui_Screen_rGKsRocq);
	lv_obj_set_width(ui_Image_rDI5MBN1,240);
	lv_obj_set_height(ui_Image_rDI5MBN1,320);
	lv_obj_set_x(ui_Image_rDI5MBN1,0);
	lv_obj_set_y(ui_Image_rDI5MBN1,0);
	lv_obj_set_style_img_recolor(ui_Image_rDI5MBN1,lv_color_make(0xff, 0xff, 0xff),LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_recolor_opa(ui_Image_rDI5MBN1,0,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_opa(ui_Image_rDI5MBN1,255,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_img_set_src(ui_Image_rDI5MBN1,&ui_img_beijing_png_png);
	lv_img_set_pivot(ui_Image_rDI5MBN1,50,50);
	lv_img_set_angle(ui_Image_rDI5MBN1,0);

	ui_Arc_3EtQ_WHD = lv_arc_create(ui_Screen_rGKsRocq);
	lv_obj_set_width(ui_Arc_3EtQ_WHD,180);
	lv_obj_set_height(ui_Arc_3EtQ_WHD,220);
	lv_obj_set_x(ui_Arc_3EtQ_WHD,30);
	lv_obj_set_y(ui_Arc_3EtQ_WHD,23);
	lv_arc_set_bg_angles(ui_Arc_3EtQ_WHD,135,45);
	lv_arc_set_range(ui_Arc_3EtQ_WHD,0,100);
	lv_arc_set_value(ui_Arc_3EtQ_WHD,30);
	lv_obj_set_style_arc_color(ui_Arc_3EtQ_WHD,lv_color_hex(0xFFFFFF),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_arc_opa(ui_Arc_3EtQ_WHD,25,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_arc_width(ui_Arc_3EtQ_WHD,18,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_arc_color(ui_Arc_3EtQ_WHD,lv_color_hex(0x03B672),LV_PART_INDICATOR | LV_STATE_DEFAULT);
	lv_obj_set_style_arc_opa(ui_Arc_3EtQ_WHD,255,LV_PART_INDICATOR | LV_STATE_DEFAULT);
	lv_obj_set_style_arc_width(ui_Arc_3EtQ_WHD,18,LV_PART_INDICATOR | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui_Arc_3EtQ_WHD,lv_color_hex(0xffffff),LV_PART_KNOB | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui_Arc_3EtQ_WHD,255,LV_PART_KNOB | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_left(ui_Arc_3EtQ_WHD,9,LV_PART_KNOB | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(ui_Arc_3EtQ_WHD,9,LV_PART_KNOB | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(ui_Arc_3EtQ_WHD,9,LV_PART_KNOB | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(ui_Arc_3EtQ_WHD,9,LV_PART_KNOB | LV_STATE_DEFAULT);
	lv_obj_set_style_border_color(ui_Arc_3EtQ_WHD,lv_color_hex(0x03B672),LV_PART_KNOB | LV_STATE_DEFAULT);
	lv_obj_set_style_border_opa(ui_Arc_3EtQ_WHD,255,LV_PART_KNOB | LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui_Arc_3EtQ_WHD,3,LV_PART_KNOB | LV_STATE_DEFAULT);

	ui_Label_sX8ziDB5 = lv_label_create(ui_Screen_rGKsRocq);
	lv_obj_set_x(ui_Label_sX8ziDB5,84);
	lv_obj_set_y(ui_Label_sX8ziDB5,74);
	lv_obj_set_width(ui_Label_sX8ziDB5,LV_SIZE_CONTENT);
	lv_obj_set_height(ui_Label_sX8ziDB5,LV_SIZE_CONTENT);
	lv_label_set_text(ui_Label_sX8ziDB5,"21");
	lv_obj_set_style_text_color(ui_Label_sX8ziDB5,lv_color_hex(0xFFFFFF),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Label_sX8ziDB5,255,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui_Label_sX8ziDB5,LV_TEXT_ALIGN_CENTER,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Label_sX8ziDB5,&lv_font_montserrat_48,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Image_wp3wpZoQ = lv_img_create(ui_Screen_rGKsRocq);
	lv_obj_set_width(ui_Image_wp3wpZoQ,36);
	lv_obj_set_height(ui_Image_wp3wpZoQ,36);
	lv_obj_set_x(ui_Image_wp3wpZoQ,194);
	lv_obj_set_y(ui_Image_wp3wpZoQ,8);
	lv_obj_set_style_img_recolor(ui_Image_wp3wpZoQ,lv_color_make(0xff, 0xff, 0xff),LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_recolor_opa(ui_Image_wp3wpZoQ,0,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_opa(ui_Image_wp3wpZoQ,255,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_img_set_src(ui_Image_wp3wpZoQ,&ui_img_dianliangzhengchang_png_png);
	lv_img_set_pivot(ui_Image_wp3wpZoQ,50,50);
	lv_img_set_angle(ui_Image_wp3wpZoQ,0);

	ui_Imgbutton_evnVpoZ1 = lv_imgbtn_create(ui_Screen_rGKsRocq);
	lv_imgbtn_set_src(ui_Imgbutton_evnVpoZ1,LV_IMGBTN_STATE_RELEASED,NULL,&ui_img_fengsu_png_png,NULL);
	lv_obj_set_width(ui_Imgbutton_evnVpoZ1,40);
	lv_obj_set_height(ui_Imgbutton_evnVpoZ1,40);
	lv_obj_set_x(ui_Imgbutton_evnVpoZ1,32);
	lv_obj_set_y(ui_Imgbutton_evnVpoZ1,250);
	lv_obj_set_style_text_color(ui_Imgbutton_evnVpoZ1,lv_color_hex(0xffffff),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Imgbutton_evnVpoZ1,255,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Imgbutton_evnVpoZ1,&lv_font_montserrat_14,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Image_ronkrDQc = lv_img_create(ui_Screen_rGKsRocq);
	lv_obj_set_width(ui_Image_ronkrDQc,40);
	lv_obj_set_height(ui_Image_ronkrDQc,40);
	lv_obj_set_x(ui_Image_ronkrDQc,173);
	lv_obj_set_y(ui_Image_ronkrDQc,250);
	lv_obj_set_style_img_recolor(ui_Image_ronkrDQc,lv_color_make(0xff, 0xff, 0xff),LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_recolor_opa(ui_Image_ronkrDQc,0,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_opa(ui_Image_ronkrDQc,255,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_img_set_src(ui_Image_ronkrDQc,&ui_img_moshi_png_png);
	lv_img_set_pivot(ui_Image_ronkrDQc,50,50);
	lv_img_set_angle(ui_Image_ronkrDQc,0);

	ui_Imgbutton_ona_PBbd = lv_imgbtn_create(ui_Screen_rGKsRocq);
	lv_imgbtn_set_src(ui_Imgbutton_ona_PBbd,LV_IMGBTN_STATE_RELEASED,NULL,&ui_img_kaiqi_png_png,NULL);
	lv_obj_set_width(ui_Imgbutton_ona_PBbd,40);
	lv_obj_set_height(ui_Imgbutton_ona_PBbd,40);
	lv_obj_set_x(ui_Imgbutton_ona_PBbd,100);
	lv_obj_set_y(ui_Imgbutton_ona_PBbd,274);
	lv_obj_set_style_text_color(ui_Imgbutton_ona_PBbd,lv_color_hex(0xffffff),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Imgbutton_ona_PBbd,255,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Imgbutton_ona_PBbd,&lv_font_montserrat_14,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Imgbutton_bj2KQu_x = lv_imgbtn_create(ui_Screen_rGKsRocq);
	lv_imgbtn_set_src(ui_Imgbutton_bj2KQu_x,LV_IMGBTN_STATE_RELEASED,NULL,&ui_img_shangjiantou_png_png,NULL);
	lv_obj_set_width(ui_Imgbutton_bj2KQu_x,24);
	lv_obj_set_height(ui_Imgbutton_bj2KQu_x,24);
	lv_obj_set_x(ui_Imgbutton_bj2KQu_x,108);
	lv_obj_set_y(ui_Imgbutton_bj2KQu_x,51);
	lv_obj_set_style_text_color(ui_Imgbutton_bj2KQu_x,lv_color_hex(0xffffff),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Imgbutton_bj2KQu_x,255,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Imgbutton_bj2KQu_x,&lv_font_montserrat_14,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Imgbutton_1Rq8MsWo = lv_imgbtn_create(ui_Screen_rGKsRocq);
	lv_imgbtn_set_src(ui_Imgbutton_1Rq8MsWo,LV_IMGBTN_STATE_RELEASED,NULL,&ui_img_xiajiantou_png_png,NULL);
	lv_obj_set_width(ui_Imgbutton_1Rq8MsWo,24);
	lv_obj_set_height(ui_Imgbutton_1Rq8MsWo,24);
	lv_obj_set_x(ui_Imgbutton_1Rq8MsWo,108);
	lv_obj_set_y(ui_Imgbutton_1Rq8MsWo,140);
	lv_obj_set_style_text_color(ui_Imgbutton_1Rq8MsWo,lv_color_hex(0xffffff),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Imgbutton_1Rq8MsWo,255,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Imgbutton_1Rq8MsWo,&lv_font_montserrat_14,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Label_OyXxwNmi = lv_label_create(ui_Screen_rGKsRocq);
	lv_obj_set_x(ui_Label_OyXxwNmi,144);
	lv_obj_set_y(ui_Label_OyXxwNmi,87);
	lv_obj_set_width(ui_Label_OyXxwNmi,LV_SIZE_CONTENT);
	lv_obj_set_height(ui_Label_OyXxwNmi,LV_SIZE_CONTENT);
	lv_label_set_text(ui_Label_OyXxwNmi,"°C");
	lv_obj_set_style_text_color(ui_Label_OyXxwNmi,lv_color_hex(0xFFFFFF),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Label_OyXxwNmi,255,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui_Label_OyXxwNmi,LV_TEXT_ALIGN_CENTER,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Label_OyXxwNmi,&lv_font_montserrat_16,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Label_3cbfZoEk = lv_label_create(ui_Screen_rGKsRocq);
	lv_obj_set_x(ui_Label_3cbfZoEk,50);
	lv_obj_set_y(ui_Label_3cbfZoEk,181);
	lv_obj_set_width(ui_Label_3cbfZoEk,LV_SIZE_CONTENT);
	lv_obj_set_height(ui_Label_3cbfZoEk,LV_SIZE_CONTENT);
	lv_label_set_text(ui_Label_3cbfZoEk,"16°C");
	lv_obj_set_style_text_color(ui_Label_3cbfZoEk,lv_color_hex(0xFFFFFF),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Label_3cbfZoEk,127,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui_Label_3cbfZoEk,LV_TEXT_ALIGN_CENTER,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Label_3cbfZoEk,&lv_font_montserrat_14,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Label_3ulSxW9v = lv_label_create(ui_Screen_rGKsRocq);
	lv_obj_set_x(ui_Label_3ulSxW9v,155);
	lv_obj_set_y(ui_Label_3ulSxW9v,183);
	lv_obj_set_width(ui_Label_3ulSxW9v,LV_SIZE_CONTENT);
	lv_obj_set_height(ui_Label_3ulSxW9v,LV_SIZE_CONTENT);
	lv_label_set_text(ui_Label_3ulSxW9v,"30°C");
	lv_obj_set_style_text_color(ui_Label_3ulSxW9v,lv_color_hex(0xFFFFFF),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Label_3ulSxW9v,127,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui_Label_3ulSxW9v,LV_TEXT_ALIGN_CENTER,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Label_3ulSxW9v,&lv_font_montserrat_14,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Label_mCYBirzL = lv_label_create(ui_Screen_rGKsRocq);
	lv_obj_set_x(ui_Label_mCYBirzL,11);
	lv_obj_set_y(ui_Label_mCYBirzL,216);
	lv_obj_set_width(ui_Label_mCYBirzL,LV_SIZE_CONTENT);
	lv_obj_set_height(ui_Label_mCYBirzL,LV_SIZE_CONTENT);
	lv_label_set_text(ui_Label_mCYBirzL,"风速：自动");
	lv_obj_set_style_text_color(ui_Label_mCYBirzL,lv_color_hex(0xFFFFFF),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Label_mCYBirzL,204,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui_Label_mCYBirzL,LV_TEXT_ALIGN_CENTER,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Label_mCYBirzL,&lv_font_montserrat_14,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Label_pNGqdf8X = lv_label_create(ui_Screen_rGKsRocq);
	lv_obj_set_x(ui_Label_pNGqdf8X,149);
	lv_obj_set_y(ui_Label_pNGqdf8X,217);
	lv_obj_set_width(ui_Label_pNGqdf8X,LV_SIZE_CONTENT);
	lv_obj_set_height(ui_Label_pNGqdf8X,LV_SIZE_CONTENT);
	lv_label_set_text(ui_Label_pNGqdf8X,"模式：自动");
	lv_obj_set_style_text_color(ui_Label_pNGqdf8X,lv_color_hex(0xFFFFFF),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Label_pNGqdf8X,204,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui_Label_pNGqdf8X,LV_TEXT_ALIGN_CENTER,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Label_pNGqdf8X,&lv_font_montserrat_14,LV_PART_MAIN | LV_STATE_DEFAULT);
}
