// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 240_320

#ifndef _UI_COMP_SCROLLDOTS_H
#define _UI_COMP_SCROLLDOTS_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Scrolldots
#define UI_COMP_SCROLLDOTS_SCROLLDOTS 0
#define UI_COMP_SCROLLDOTS_D1 1
#define UI_COMP_SCROLLDOTS_D2 2
#define UI_COMP_SCROLLDOTS_D3 3
#define UI_COMP_SCROLLDOTS_D4 4
#define UI_COMP_SCROLLDOTS_D5 5
#define UI_COMP_SCROLLDOTS_D6 6
#define _UI_COMP_SCROLLDOTS_NUM 7
lv_obj_t * ui_Scrolldots_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
