// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 240_320

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_Label18;

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
lv_obj_t * ui_Screen1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Switch2;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label33;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Button6;
lv_obj_t * ui_Button7;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Button15;
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Dropdown1;

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Button10;
lv_obj_t * ui_Button8;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label40;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Panel7;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
lv_obj_t * ui_Button12;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label17;
void ui_event_Button20(lv_event_t * e);
lv_obj_t * ui_Button20;

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t * ui_Screen5;
lv_obj_t * ui_Panel4;
void ui_event_Button19(lv_event_t * e);
lv_obj_t * ui_Button19;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Label35;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Label39;

// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
lv_obj_t * ui_Screen6;
lv_obj_t * ui_Panel5;
void ui_event_Button17(lv_event_t * e);
lv_obj_t * ui_Button17;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Panel12;
void ui_event_TextArea_ssid(lv_event_t * e);
lv_obj_t * ui_TextArea_ssid;
void ui_event_TextArea_password(lv_event_t * e);
lv_obj_t * ui_TextArea_password;
lv_obj_t * ui_Keyboard2;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Button18;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Label32;

// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
void ui_event_Screen7(lv_event_t * e);
lv_obj_t * ui_Screen7;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label42;
lv_obj_t * ui_Label43;
lv_obj_t * ui_Label45;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_240x[1] = {&ui_img_240x320_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
#define SEC_TO_CHANGE_SCREEN_SAVER 30
extern uint8_t no_touch;
static uint8_t is_ScreenSaver = 0;
uint8_t sec = 0;
uint8_t min = 0;
uint8_t hour = 0;
///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 300, 3000);
    }
}
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
        io2_set(1);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        play_voice_open();
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        play_voice_close();
    }
}
void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        play_voice_open();
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        play_voice_close();
    }
}
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0);
    }
}
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        GLB_SW_System_Reset();
    }
}
void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_Button20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_Button19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_TextArea_ssid(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_TextArea_ssid);
    }
}
void ui_event_TextArea_password(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_TextArea_password);
    }
}
void ui_event_Screen7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
        io2_set(0);
        is_ScreenSaver = 0;
    }
}
void ui_event_Button18(lv_event_t * e)
{
    char *pStr;
    char Ssid[50] = {0};
    char Password[30] = {0};
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        pStr = lv_textarea_get_text(ui_TextArea_ssid);
        printf("ssid:%s\r\n", pStr);
        memset(Ssid, 0, sizeof(Ssid));
        strcpy(Ssid, pStr);
        pStr = lv_textarea_get_text(ui_TextArea_password);
        printf("pwd:%s\r\n", pStr);
        memset(Password, 0, sizeof(Password));
        strcpy(Password, pStr);

        if(wifi_connect(Ssid, Password) == 0){
            lv_label_set_text(ui_Label32, "status: Ok");
        }
        else{
            lv_label_set_text(ui_Label32, "status: Fail");
        }
    }

}

///////////////////// SCREENS ////////////////////

#include "bflb_timestamp.h"
bflb_timestamp_t timestamp = {0};
void sntp_set_time(uint32_t sntp_time, uint32_t fac)
{
    uint32_t stamp;
    uint32_t daysNumber;
    uint32_t lYearTemp = 1970;
    uint8_t ucMonthTemp = 1;
    

    stamp = sntp_time - 2208988800;
    // stamp += UTC_CHINA * 3600;

    bflb_timestamp_utc2time(stamp, &timestamp);

    hour = timestamp.hour;
    min = timestamp.min;
    sec = timestamp.sec;
    printf("hour:%d, min:%d, sec:%d\r\n", timestamp.hour, timestamp.min, timestamp.sec);

}

void update_time(void)
{
    
    if(sec >= 59)
    {
        sec = 0;
        if(min >= 59)
        {
            min = 0;
            if(hour >= 23)
            {
                hour = 0;
            }
            else 
            {
                hour++;
            }
            
        }
        else
        {
            min++;
        }
        
    }
    else
    {
        sec++;
    }
    
    
    
}
void SecTimer_cb(lv_timer_t * t)
{
    uint8_t stime[9];

    no_touch++;
    if(no_touch >= SEC_TO_CHANGE_SCREEN_SAVER && is_ScreenSaver == 0){
        is_ScreenSaver = 1;
        _ui_screen_change(ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
        io2_set(1);
    }
    // if(no_touch < 3 && is_ScreenSaver == 1){
    //     is_ScreenSaver = 0;
    //     _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    // }
    update_time();
    snprintf(stime, 9, "%02d:%02d:%02d", hour, min, sec);
    lv_label_set_text(ui_Label4, stime);
    lv_label_set_text(ui_Label13, stime);
    lv_label_set_text(ui_Label10, stime);
    lv_label_set_text(ui_Label21, stime);

    lv_label_set_text_fmt(ui_Label6, "%02d-%02d", timestamp.mon, timestamp.mday);
    lv_label_set_text_fmt(ui_Label11, "%02d-%02d", timestamp.mon, timestamp.mday);
    lv_label_set_text_fmt(ui_Label23, "%02d-%02d", timestamp.mon, timestamp.mday);
    lv_label_set_text_fmt(ui_Label43, "%02d-%02d", timestamp.mon, timestamp.mday);
    // lv_label_set_text_fmt(ui_Label6, "");
    // lv_label_set_text_fmt(ui_Label11, "");
    // lv_label_set_text_fmt(ui_Label23, "");
    // lv_label_set_text_fmt(ui_Label43, "");
    
}

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen4_screen_init();
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen5_screen_init();
    ui_Screen6_screen_init();
    ui_Screen7_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen4);

    lv_timer_create(SecTimer_cb, 1000, NULL);
}
