// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 240_320

#ifndef _240_320_UI_H
#define _240_320_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Label18;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
void ui_event_Button1(lv_event_t * e);
void ui_event_Button5(lv_event_t * e);
void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label33;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Dropdown1;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel7;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label17;
void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Panel4;
void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label39;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Panel5;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Panel12;
void ui_event_TextArea_ssid(lv_event_t * e);
extern lv_obj_t * ui_TextArea_ssid;
void ui_event_TextArea_password(lv_event_t * e);
extern lv_obj_t * ui_TextArea_password;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
void ui_event_Button18(lv_event_t * e);

// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
void ui_event_Screen7(lv_event_t * e);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_ai_png);    // assets\ai.png
LV_IMG_DECLARE(ui_img_240x320_png);    // assets\240x320.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
