// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 240_320

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#define play_voice_open() 
#define play_voice_close() 
#define play_voice_open_8388() 
#define play_voice_close_8388() 
// extern void play_voice_open(void);
// extern void play_voice_close(void);
// extern void play_voice_open_8388(void);
// extern void play_voice_close_8388(void);
extern void io2_set(uint8_t value);
extern uint8_t wifi_connect(char *ssid, char *passwd);
extern GLB_SW_System_Reset();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
