// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 240_320

#include "../ui.h"

void ui_comp_Scrolldots_create_hook(lv_obj_t * comp)
{
}
